spring.application.name=zuborarecipeapp

# 1. DBへの接続設定（環境変数から読み込む設定）
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. MyBatisの設定
mybatis.mapper-locations=classpath:com/example/zuborarecipeapp/repository/RecipeMapper.xml
mybatis.type-aliases-package=com.example.zuborarecipeapp.entity

# 3. ログ設定
logging.level.com.example.zuborarecipeapp.repository=DEBUG
